#9-1 PROGRAMMING EXERCISE
#WRITE A PROGRAM THAT CREATES A DICTIONARY CONTAINING COURSE NUMBERS
#AND THE ROOM NUMBERS OF THE ROOMS WHERE THE COURSES MEET. THE DICTIONARY SHOULD 
#HAVE THE FOLLOWING KEYVALUE PAIRS:
#COURSE NUMBER(KEY): CS101, CS102, CS103, NT110, CM241
#ROOM NUMBER(VALUE): 3004, 4501, 6755, 1244, 1411
#THE PROGRAM SHOULD ALSO CREATE A DICTIONARY CONTAINING COURSE NUMBERS
#AND THE NAME OF THE INSTRUCTORS FOR EACH COURSE
#INSTRUCTOR (VALUE): HAYNES, ALVARADO, RICH, BURKE, LEE
#THE PROGRAM SHOULD ALSO CREATE A DICTIONARY FOR COURSE NUMBERS AND MEETING TIMES:
#MEETING TIME(VALUE): 8:00 A.M., 9:00 A.M., 10:00 A.M., 11:00 A.M., 1:00PM
#THE PROGRAM SHOULD LET THE USER ENTER A COURSE NUMBER, AND THEN IT SHOULD DISPLAY THE COURSE'S ROOM NUMBER, INSTRUCTOR,
#AND MEETING TIME


# CREATE DICTIONARY FOR COURSE ROOM(KEY) AND ROOM NUMBER (VALUE)
course_rooms = {
    'CS101': 3004,
    'CS102': 4501,
    'CS103': 6755,
    'NT110': 1244,
    'CM241': 1411
}

# CREATE DICTIONARY F0R COURSE NUMBERS(KEY) AND INSTRUCTORS(VALUE)
course_instructors = {
    'CS101': 'Haynes',
    'CS102': 'Alvarado',
    'CS103': 'Rich',
    'NT110': 'Burke',
    'CM241': 'Lee'
}

# CREATE DICTIONARY FOR COURSE NUMBER(KEY) AND MEETING TIME(VALUE)
course_times = {
    'CS101': '8:00 A.M.',
    'CS102': '9:00 A.M.',
    'CS103': '10:00 A.M.',
    'NT110': '11:00 A.M.',
    'CM241': '1:00 P.M.'
}

# ASK FOR USER INPUT
course_number = input("ENTER COURSE NUMBER (EX: CS101): ")

# CHECK IF NUMBER EXISTS IN DICTIONARIES
if course_number in course_rooms and course_number in course_instructors and course_number in course_times:
    # DISPLAY RESULTS
    print(f"COURSE NUMBER: {course_number}")
    print(f"ROOM NUMBER: {course_rooms[course_number]}")
    print(f"INSTRUCTOR: {course_instructors[course_number]}")
    print(f"MEET TIME: {course_times[course_number]}")
else:
    print("NO COURSE NUMBERS FOUND")